### PR TITLE
Fix Clippy errors in tests and enforce Clippy checks in CI

### LINKED ISSUE #226: Fix Clippy errors in tests and enforce Clippy checks in CI
We haven’t checked Clippy lints in test code before, but now it’s time to do so.

### PR DESCRIPTION
**Pull request by jinjoolee07**
Close #226

### CODE REVIEW

File: src/input.rs [hunk 1]
```diff
@@ -77,7 +77,8 @@ mod tests {
     }
 }
 
-fn _cal_index_first_ver(base_index: Option<usize>, layer_index: usize) -> usize {
+#[cfg(test)]
+fn cal_index_first_ver(base_index: Option<usize>, layer_index: usize) -> usize {
```
Comment (sehkone) [inline src/input.rs:81]: I think it would look better to move the two methods, `cal_index_first_ver` and `cal_index_with_bit_op`, between the line 48 and 49. It should require adjustments regarding paths of variables and methods as well as the declaration of `num_traits::ToPrimitive` inside the `tests`.

Comment (jinjoolee07) [reply src/input.rs]: Thank you for the suggestion! I've made the changes as you recommended and adjusted the paths. Let me know if there's anything else!

File: src/input.rs [hunk 2]
```diff
@@ -46,20 +46,52 @@ static MAX_NUM_OF_LAYER: LazyLock<BigUint> =
 
 #[cfg(test)]
 mod tests {
+    use num_traits::ToPrimitive;
+    #[cfg(test)]
```
Comment (sehkone) [inline src/input.rs:50]: I think this line is not necessary.

File: src/input.rs [hunk 3]
```diff
@@ -46,20 +46,52 @@ static MAX_NUM_OF_LAYER: LazyLock<BigUint> =
...
+                panic!("Too many levels in hierarchy of input items");
+            };
+            let base = 2_usize.pow(super::POWER_OF_MAX_NUM_OF_LAYER).pow(base + 1);
+            base_index + base * (1 + layer_index)
+        } else {
+            layer_index
+        }
+    }
+
+    #[cfg(test)]
```
Comment (sehkone) [inline src/input.rs:70]: The same as the above

**Review by sehkone — APPROVED** [review]
