### PR TITLE
Fix error border & header font in modal

### LINKED ISSUE #270: Fix Error Border & Header Font in New Network Modal
Description
Fix the error border wrapping around the helper text and update the font to match other headers.

- Error Border Issue → The red error border should only wrap around the input field, not the helper text.
- Header Font Weight Issue → Headers (Network/IP Details, Customer, Tag) should have 4px bottom spacing and font weight 500 for consistency.

### PR DESCRIPTION
**Pull request by jinjoolee07**
Close #270

### CODE REVIEW

File: src/input/host_network.rs [hunk 1]
```diff
@@ -292,9 +294,14 @@ where
...
         );
+        let class = if ctx.props().is_required {
+            "input-host-network-group-required"
+        } else {
+            "host-network-group-input"
+        };
         html! {
             <>
-                <div class="host-network-group-input" style={style}>
+                <div class={class} style={style}>
```
Comment (sehkone) [inline src/input/host_network.rs:304]: `<div {class} {style}>` would be better.

File: src/input/user_input.rs [hunk 2]
```diff
@@ -849,33 +849,27 @@ where
...
-                            verify_to_save={self.verify_host_network_group}
-                        />
-                    </div>
+                    <HostNetworkHtml<Self>
+                        txt={ctx.props().txt.clone()}
+                        language={ctx.props().language}
+                        rerender_serial={self.rerender_serial_host_network}
+                        kind={kind}
+                        num={num}
+                        width={width}
```
Comment (sehkone) [inline src/input/user_input.rs:863]:
```
{kind}
{num}
{width}
```
I think the above is simpler.

File: src/input/host_network.rs (hunk 1 above)
Comment (jinjoolee07) [reply src/input/host_network.rs]: Done

File: src/input/user_input.rs (hunk 2 above)
Comment (jinjoolee07) [reply src/input/user_input.rs]: Done

**Review by sophie-cluml — APPROVED** [review]
