### PR TITLE
Fix missing duplicate validation in admin modals

### LINKED ISSUE #277: Duplicate Validation Missing in Admin Modals
Description
When creating a new entry in any of the Admin modals (Node, Customer, Network, Account), the error message is missing or not functioning correctly when a duplicate name or other unique field is entered. This issue leads to users not being informed why the action is blocked.

### PR DESCRIPTION
**Pull request by jinjoolee07**
Close #277

### CODE REVIEW

File: src/input/component.rs [hunk 1]
```diff
@@ -1182,7 +1182,7 @@ where
                                 }
                             }
                             if !different {
-                                self.unique_msg.insert(BigUint::from(index + 1));
```
Comment (sophie-cluml) [inline src/input/component.rs:1185]: I personally believe we should take a very cautious approach when removing a number that could potentially be a magic number. So I'd like to review this PR carefully. @jinjoolee has shared her research with me through a private channel, including context and supporting evidence that explain her confidence in making this change. I’ll take the time to go through it thoroughly.

That said, since this +1 was originally introduced by @sehkone and given his deep understanding of the logic as long as this repository, I’d greatly appreciate it if Kone could share any insights or rationale behind the decision, in case there is important context we might miss, or at least save our time in huge amount.

Comment (sehkone) [reply src/input/component.rs:1185]: @jinjoolee07, could you explain why you left out the +1 part? Did you encounter any incorrect results during testing?

Comment (sehkone) [reply src/input/component.rs:1185]: I remember that the +1 part is for the first-layer items in the user input. These items start at 1, not 0, whereas any child components start at 0. The reason the first-layer items start at 1 is because we need to assign unique indices to all items, which can’t be guaranteed under the current design if we start from 0.

Comment (jinjoolee07) [reply src/input/component.rs:1185]: Yes — while testing, I noticed that the unique validation message wasn’t showing up correctly for the first field (like Customer Name). From the debug output, it looked like `unique_msg` was checking for index 1, but the actual index rendered in the UI was 0, so the validation didn’t trigger properly.

After removing the +1, the validation message showed up as expected. From what I could tell, the `cal_index` function already account for indexing, even in nested structures, so the extra +1 seemed to throw off the alignment for top-level fields.

Comment (sehkone) [reply src/input/component.rs:1185]: This seems like a significant bug that I hadn’t considered before. Could you show me the scenario where it occurs? We should set up a meeting.

Comment (sehkone) [reply src/input/component.rs:1185]: From our screen-sharing discussion, I realized that the magic number was used in the previous implementation. The current code, which was significantly refactored, no longer needs that kind of workaround, thanks to the `cal_index` method. The problem is that the part @jinjoolee07 found hadn’t been updated accordingly during the refactoring, and I had completely forgotten about it. I really appreciate that she fixed such a critical issue. This PR absolutely makes sense.

**Comment by jinjoolee07** [comment]
@sophie-cluml Appreciate the reminder — changelog is updated now!

**Review by sophie-cluml — APPROVED** [review]
