### PR TITLE
Fix Clippy warnings caused by rustc 1.86.0

### LINKED ISSUE #290: Fix Clippy warnings caused by rustc 1.86.0
EOM

### PR DESCRIPTION
**Pull request by Goder-0**
## Related Issues
closes #290  
## PR Description
- Remove unnecessary Semicolon
- Replace `map_or` with ~`is_some_and` and `is_none_or`~ a simpler comparison
- Fix for `format_push_string` lint
  - Using `format!` together with `push_str` can cause unnecessary allocations compared to using `write!`.
  - For performance reference: https://play.rust-lang.org/?version=nightly&mode=release&edition=2018&gist=daed734101a8d8bc0c6a7bd811154504

### CODE REVIEW

File: src/input/recursive.rs [hunk 1]
```diff
@@ -621,14 +621,14 @@ where
...
-            let all_empty = row.iter().all(|x| x.map_or(false, |x| x));
+            let all_empty = row.iter().all(|x| x.is_some_and(|x| x));
             if !all_empty || config.ess.required && row_index == 0 {
                 // HIGHLIGHT: If the entire row is empty, this row will be ignored. Only when more
                 // than one column is not empty, the other elements being empty need to be checked.
                 for ((col_index, data_empty), data_required) in
                     row.iter().enumerate().zip(required.iter())
                 {
-                    if data_empty.map_or(true, |x| x) && *data_required {
+                    if data_empty.is_none_or(|x| x) && *data_required {
```
Comment (sehkone) [inline src/input/recursive.rs:631]: Although this is good enough, the following would be simpler and clearer:
```
    if data_empty != Some(false) && ...
```
This might have very small advantage regarding performance.

File: src/input/recursive.rs [hunk 2]
```diff
@@ -621,14 +621,14 @@ where
         })
         .collect::<Vec<Vec<Option<bool>>>>();
         for (row_index, row) in empty.iter().enumerate() {
-            let all_empty = row.iter().all(|x| x.map_or(false, |x| x));
+            let all_empty = row.iter().all(|x| x.is_some_and(|x| x));
```
Comment (sehkone) [inline src/input/recursive.rs:624]: Just like the below comment, this could be the following:

```
    let ... (|x| x == Some(true));
```

File: src/input/recursive.rs [hunk 3]
```diff
@@ -436,7 +436,7 @@ where
                                 && self
                                     .verification_host_network
                                     .get(&this_index)
-                                    .is_some_and(|v| v.map_or(true, |v| v))
+                                    .is_some_and(|v| v.is_none_or(|v| v))
```
Comment (sehkone) [inline src/input/recursive.rs:439]: Like the below comments,

```
    .is_some_and(|v| v != Some(true))
```

File: src/input/recursive.rs (hunk 1 above)
Comment (Goder-0) [reply src/input/recursive.rs]: Updated as per your suggestion, thank you!

File: src/input/recursive.rs (hunk 2 above)
Comment (sehkone) [reply src/input/recursive.rs]: @Goder-0 

It looks like you resolved this conversation. But, one of our rule says it should be resolved by the commenter. Could you unresolve it?

Comment (Goder-0) [reply src/input/recursive.rs]: @sehkone  Sorry, I canceled the resolution. I’ll be more careful next time.

**Review by sehkone — APPROVED** [review]

**Comment by sehkone** [comment]
@Goder-0 
A PR must be handled by the person(s) who was designated before, since merging code into the main branch requires extreme caution. Could you please remove yourself from the assignee of this PR?

**Comment by Goder-0** [comment]
> @Goder-0 A PR must be handled by the person(s) who was designated before, since merging code into the main branch requires extreme caution. Could you please remove yourself from the assignee of this PR?

@sehkone  Apologies for the oversight. I’ve removed myself from the assignee, and I’ll be more careful next time.

**Comment by sehkone** [comment]
@Goder-0,

I don't think the commit messages can be combined into one, because each is not important enough. According to one of our rules, it would be better to leave just one commit message.

**Comment by Goder-0** [comment]
> I think the commit messages can be combined into one, because each is not important enough. According to one of our rules, it would be better to leave just one commit message.

@sehkone Thanks for the feedback. I've squashed the commits into a single one as per your comment. Let me know if there’s anything else I should address.

**Review by sehkone — APPROVED** [review]
