### PR TITLE
Respect second-layer edit state for inputs

### LINKED ISSUE #460: Fix edit-mode detection logic to rely on dialog mode
### Description
Currently, the edit-mode detection logic incorrectly causes "Add" mode to be treated as "Edit" mode in some cases.
As a result, text input fields with the `immutable: true` attribute are rendered as disabled even in "Add" mode, preventing users from entering values such as IDs.

### Root Cause
The is_edit_mode flag is currently determined by:
```
let is_edit_mode = ctx.props().input_id.is_some();
```
When the user clicks "Edit" or "Delete", `ctx.props().input_id` (hereafter `input_id`) is set to `Some`. However, it is never reset back to `None` afterward. As a result, the application continues to treat the state as "Edit" even when switching to "Add".

### Proposed Solution
Instead of relying on whether `input_id` is `Some`, the `is_edit_mode` logic should be based on dialog mode. This makes the behavior more intuitive and removes the need to explicitly reset `input_id` after events such as Edit/Delete/Escape.

### PR DESCRIPTION
**Pull request by jadenow**
- derived text input edit mode from `input_second_id` when present
- stopped passing `input_id` during add flows so fields stay writable

Closes #460

### CODE REVIEW

File: src/list/whole/component.rs [hunk 1]
```diff
@@ -951,3 +948,21 @@ where
         }
     }
 }
+
+impl<T> Model<T>
+where
+    T: Clone + Component + PartialEq,
+    <T as Component>::Message: Clone + PartialEq,
+{
+    fn current_input_id(&self, ctx: &Context<Self>) -> Option<String> {
```
Comment (danbi2990) [inline src/list/whole/component.rs:957]: I don't think this needs to be extracted into a method. As long as we keep the declaration at line 781, there's no reuse required.

Extraction decisions can be subtle, but in this case:

- There's no actual reuse for this method.
- The added boilerplate (`impl<T> Model<T> ...`) makes the code harder to read.

**Review by danbi2990 — APPROVED** [review]

File: CHANGELOG.md [hunk 2]
```diff
@@ -50,6 +50,8 @@ Versioning](https://semver.org/spec/v2.0.0.html).
 - Fixed overflow in `searchable-select-list-down` CSS to remove horizontal scrollbar.
 - Fixed mini select styling for `pumpkin` feature by moving some inline colors
   to CSS, enabling proper dark/light mode integration.
+- Fixed an issue where Add mode was incorrectly detected as Edit mode if
+  `input_id` remained set after Edit/Delete actions.
```
Comment (sophie-cluml) [inline CHANGELOG.md:54]: If terms like Add, Edit, Edit/Delete are references to code, please enclose them in backticks. Otherwise, please write them according to standard English grammar.

**Comment by sophie-cluml** [comment]
Could you rebase please? If CI fails even after rebasing, I kindly ask you to check the CI failure please.

**Comment by jadenow** [comment]
@sophie-cluml 
I’ve rebased my branch onto the latest main branch. The CI check has now passed successfully.

**Review by sophie-cluml — APPROVED** [review]
